client_config_backend: settings
client_config:
  client_id: "655559773285-g254rvt7msdvbe8c4m9movdgd0ig1ioj.apps.googleusercontent.com"
  client_secret: "aBhPcIllQ1g55eQYWGFKtuqE"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive